---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: ''
  label: Test
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - BRIDGETOWN_ENV=staging
  - NODE_ENV=staging
  preview_output_directory: public
  install_dependencies_command: bundle install --path vendor/bundle && npm install
  preview_docker_image: forestryio/ruby:2.6-node10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry-serve
