---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: src/_podcasts
  label: Podcasts
  create: all
  match: "**/*"
  new_doc_ext: ''
  templates:
  - page
- type: directory
  path: src/_data
  label: Data
  create: all
  match: "**/*"
  new_doc_ext: yml
- type: document
  path: README.md
  label: Help
  read_only: true
- type: document
  path: src/index.md
  label: Home
- type: directory
  path: src/_posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: ''
  label: Test
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - BRIDGETOWN_ENV=staging
  - NODE_ENV=staging
  preview_output_directory: public
  install_dependencies_command: bundle install --path vendor/bundle && npm install
  preview_docker_image: forestryio/ruby:2.6-node10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
